To Do List Interactive Pull Request
YoutLone/To-Do-List pull request #3
Opened 2023-06-08 10:48 UTC by YoutLone

### ToDoList (interactive) :

 In this project I :
- setup webpack base structure
- add todo-task.js file in modules folder to make interactive
- setup linter to check the syntax error

2023-06-08 11:25 UTC, wayungi requested changes
Hi @YoutLone , 

![image](https://user-images.githubusercontent.com/99656687/234198503-c41d0396-d5b0-4466-8ed1-959de33796fa.png)


**Congratulations on the good job done so far!** 🤝 

There are some issues that you still need to work on to go to the next project but you are almost there! 😄 

## Highlights ⚡ ⚡ 
- [ ] All linter checks are passing ✔️ 
- [ ]  Correct GitHub flow ✔️ 
- [ ]  README is well written ✔️ 
 
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-08 11:25 UTC, wayungi commented on src/modules/todo-task.js
> +    console.log(this.checked);
- [ ] Do not commit console.log to your repo. It’s ugly, it kills performance and it can make confidential data be visible to anyone using the browser tools to look at your website. 😢

2023-06-08 11:25 UTC, wayungi commented on src/modules/add-remove.js
> +  }
- [ ] This function is supposed to only delete all tasks marked as completed. For now, it removes everything from the DOM. These removed items later return twice on page refresh. Please fix this.n 😺

2023-06-09 11:14 UTC, aamirkhan2478 approved these changes
Hi @YoutLone , 

![GIF](https://www.funimada.com/assets/images/cards/big/congrats-7.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ You used Gitflow correctly :+1: 
✅ No linter error :+1: 
✅ Good commit messages :+1: 
✅ Good descriptive PR :+1: 
✅ Well done :clap: you did all changes given by the previous reviewer :+1: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-09 11:16 UTC, merged